//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Lab_PSD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsCart
    {
        public int CartID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> SuplementID { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual MsSupplement MsSupplement { get; set; }
        public virtual MsUser MsUser { get; set; }
    }
}
